### ISSUE TITLE
Packaging .pxd files

### ISSUE THREAD

**Issue by chamakuri-vineel** [jborean93/pykrb5#60]
Hi, Thanks for writing this library,  It is very useful. I am planning to build a new python extension module and it needs access to some of the extension types used in `pykrb5`. I want to access the Cython level functions and attributes but currently I see that `pykrb5` doesn't ship it's `.pxd` files. Adding those files will be really helpful as I don't have to re-implement them again. Do you have any plans of shipping `.pxd` files?

Thanks,
Chamakuri Vineel

**Comment by jborean93** [comment]
The published sdist contains both the `.pyx` and `.pxd` files. I don't include them in the wheels because it contains the already compiled code for a particular platform and I typically don't include the source for them in a wheel.

Also keep in mind the interfaces of these classes are not publicly documented so can (and has changed) over a release.

**Comment by chamakuri-vineel** [comment]
Thanks for the details.
